version: '3.8'

services:
  api-gateway:
    extra_hosts:
      - "db-server:host-gateway"
    container_name: api-gateway
    build: ./api-gateway
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8000:8000"
    volumes:
      - ./api-gateway:/app

  auth-service:
    extra_hosts:
      - "db-server:host-gateway"
    container_name: auth-service
    build: ./auth-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8008:8000"
    volumes:
      - ./auth-service:/app

  book-service:
    extra_hosts:
      - "db-server:host-gateway"
    container_name: book-service
    build: ./book-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8003:8000"
    volumes:
      - ./book-service:/app

  cart-service:
    extra_hosts:
      - "db-server:host-gateway"
    container_name: cart-service
    build: ./cart-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8002:8000"
    volumes:
      - ./cart-service:/app

  catalog-service:
    extra_hosts:
      - "db-server:host-gateway"
    container_name: catalog-service
    build: ./catalog-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8009:8000"
    volumes:
      - ./catalog-service:/app

  comment-rate-service:
    extra_hosts:
      - "db-server:host-gateway"
    container_name: comment-rate-service
    build: ./comment-rate-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8007:8000"
    volumes:
      - ./comment-rate-service:/app

  customer-service:
    extra_hosts:
      - "db-server:host-gateway"
    container_name: customer-service
    build: ./customer-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8001:8000"
    volumes:
      - ./customer-service:/app

  manager-service:
    extra_hosts:
      - "db-server:host-gateway"
    container_name: manager-service
    build: ./manager-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8010:8000"
    volumes:
      - ./manager-service:/app

  order-service:
    extra_hosts:
      - "db-server:host-gateway"
    container_name: order-service
    build: ./order-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8004:8000"
    volumes:
      - ./order-service:/app

  pay-service:
    extra_hosts:
      - "db-server:host-gateway"
    container_name: pay-service
    build: ./pay-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8005:8000"
    volumes:
      - ./pay-service:/app

  recommender-ai-service:
    extra_hosts:
      - "db-server:host-gateway"
    container_name: recommender-ai-service
    build: ./recommender-ai-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8011:8000"
    volumes:
      - ./recommender-ai-service:/app

  ship-service:
    extra_hosts:
      - "db-server:host-gateway"
    container_name: ship-service
    build: ./ship-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8006:8000"
    volumes:
      - ./ship-service:/app

  staff-service:
    extra_hosts:
      - "db-server:host-gateway"
    container_name: staff-service
    build: ./staff-service
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8012:8000"
    volumes:
      - ./staff-service:/app
    
  # Thêm service này vào chung mâm với các microservice khác
  db-server:
    image: mysql:8.0  # Thay bằng postgres nếu dự án của bạn xài PostgreSQL
    container_name: db-server
    environment:
      MYSQL_ROOT_PASSWORD: "123456" # Điền ĐÚNG mật khẩu bạn đang setup trong file settings.py ở máy local
      # Nếu có nhiều database rỗng cần tạo sẵn, bạn có thể tạo thủ công sau.
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

# Khối volumes này nằm ở cuối cùng file, sát lề trái hoàn toàn
volumes:
  db_data: