# Generated by Django 6.0.3 on 2026-03-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('score', models.FloatField(default=1.0)),
                ('reason', models.CharField(default='Based on your view history', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
